//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""fca56c6f-38ed-4ad6-b0cd-18c2c1540050"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6ab2692f-04a3-45bf-91ed-1049684c153d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""0bc42058-f21b-42c4-8685-44727c727c42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapWeapons"",
                    ""type"": ""Value"",
                    ""id"": ""e89ae6a1-725f-43a5-a9fd-9d46fe268406"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""1438e75d-1a7b-43d4-a63e-2931c87cdb57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Chainsaw"",
                    ""type"": ""Button"",
                    ""id"": ""052eadd0-209a-4aec-8bc2-32fa55f17f76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pistol"",
                    ""type"": ""Button"",
                    ""id"": ""3448f120-6389-49cb-a9fe-b6116244e515"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MachineGun"",
                    ""type"": ""Button"",
                    ""id"": ""0bde1d21-9937-4265-bc19-b9958c195282"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightningGun"",
                    ""type"": ""Button"",
                    ""id"": ""521962ed-279f-4839-9fb5-ecd325454900"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RailGun"",
                    ""type"": ""Button"",
                    ""id"": ""7822aadf-94dd-4b3f-aa9a-f486ec67962a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shotgun"",
                    ""type"": ""Button"",
                    ""id"": ""5e32c8f7-7e2c-4559-bf27-6b004bba42cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RocketLauncher"",
                    ""type"": ""Button"",
                    ""id"": ""7b45e693-8b96-49da-88e2-fd572bdace87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ultimate"",
                    ""type"": ""Button"",
                    ""id"": ""29d92e5a-8ce3-478e-9cd3-96fae8ef0048"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""0270a052-7c37-44d7-8cf3-74753fd2e6cf"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8156680b-b608-45c9-bfa2-67c63894440e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7a39b2c8-d0ce-4524-8d00-729e09e591ee"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""05cbcabc-f923-405d-8eb0-c2532501d133"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a290368c-b983-4dae-bba7-befa7c652eeb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""66b13898-fb17-4b6f-8f4f-8e37fa34bf71"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0c441511-01ef-42ab-b5ab-ba390610d6c9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""424c61c3-3672-4ddd-af09-1090a9c16a84"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d7a34a5f-fcf7-4842-9c34-f27a3a9cce2b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""899b7ed5-d854-4f65-bf1c-c739495463b9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1e0142a8-9212-4c12-ac3f-759abc99eff8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b723206-63f4-4f40-b5d5-ea295799057c"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c16d5e70-2784-4d85-86d8-c33e64839859"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapWeapons"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58fdec0f-0550-4113-b593-a4ed05e2158f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c543585b-462f-42f8-88ea-c66995ed6cf1"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Chainsaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b4f78cd-5560-47a0-b19e-98fde8b5ffb0"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pistol"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23b62ae7-a65a-4d25-aba5-145ee2bbb0f4"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MachineGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6643e5ea-bd44-487e-9cd3-298018dcfb04"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightningGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57c9018a-cdc0-43c7-a67f-857721aa91ba"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RailGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7861aa0-31c9-4629-a2a2-15ae1f93955a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shotgun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77f7aee0-038c-4770-9b66-772d995b81ef"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RocketLauncher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67d870c7-b5fe-434a-9e09-5c4376def558"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_SwapWeapons = m_Player.FindAction("SwapWeapons", throwIfNotFound: true);
        m_Player_Fire = m_Player.FindAction("Fire", throwIfNotFound: true);
        m_Player_Chainsaw = m_Player.FindAction("Chainsaw", throwIfNotFound: true);
        m_Player_Pistol = m_Player.FindAction("Pistol", throwIfNotFound: true);
        m_Player_MachineGun = m_Player.FindAction("MachineGun", throwIfNotFound: true);
        m_Player_LightningGun = m_Player.FindAction("LightningGun", throwIfNotFound: true);
        m_Player_RailGun = m_Player.FindAction("RailGun", throwIfNotFound: true);
        m_Player_Shotgun = m_Player.FindAction("Shotgun", throwIfNotFound: true);
        m_Player_RocketLauncher = m_Player.FindAction("RocketLauncher", throwIfNotFound: true);
        m_Player_Ultimate = m_Player.FindAction("Ultimate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_SwapWeapons;
    private readonly InputAction m_Player_Fire;
    private readonly InputAction m_Player_Chainsaw;
    private readonly InputAction m_Player_Pistol;
    private readonly InputAction m_Player_MachineGun;
    private readonly InputAction m_Player_LightningGun;
    private readonly InputAction m_Player_RailGun;
    private readonly InputAction m_Player_Shotgun;
    private readonly InputAction m_Player_RocketLauncher;
    private readonly InputAction m_Player_Ultimate;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @SwapWeapons => m_Wrapper.m_Player_SwapWeapons;
        public InputAction @Fire => m_Wrapper.m_Player_Fire;
        public InputAction @Chainsaw => m_Wrapper.m_Player_Chainsaw;
        public InputAction @Pistol => m_Wrapper.m_Player_Pistol;
        public InputAction @MachineGun => m_Wrapper.m_Player_MachineGun;
        public InputAction @LightningGun => m_Wrapper.m_Player_LightningGun;
        public InputAction @RailGun => m_Wrapper.m_Player_RailGun;
        public InputAction @Shotgun => m_Wrapper.m_Player_Shotgun;
        public InputAction @RocketLauncher => m_Wrapper.m_Player_RocketLauncher;
        public InputAction @Ultimate => m_Wrapper.m_Player_Ultimate;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @SwapWeapons.started += instance.OnSwapWeapons;
            @SwapWeapons.performed += instance.OnSwapWeapons;
            @SwapWeapons.canceled += instance.OnSwapWeapons;
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
            @Chainsaw.started += instance.OnChainsaw;
            @Chainsaw.performed += instance.OnChainsaw;
            @Chainsaw.canceled += instance.OnChainsaw;
            @Pistol.started += instance.OnPistol;
            @Pistol.performed += instance.OnPistol;
            @Pistol.canceled += instance.OnPistol;
            @MachineGun.started += instance.OnMachineGun;
            @MachineGun.performed += instance.OnMachineGun;
            @MachineGun.canceled += instance.OnMachineGun;
            @LightningGun.started += instance.OnLightningGun;
            @LightningGun.performed += instance.OnLightningGun;
            @LightningGun.canceled += instance.OnLightningGun;
            @RailGun.started += instance.OnRailGun;
            @RailGun.performed += instance.OnRailGun;
            @RailGun.canceled += instance.OnRailGun;
            @Shotgun.started += instance.OnShotgun;
            @Shotgun.performed += instance.OnShotgun;
            @Shotgun.canceled += instance.OnShotgun;
            @RocketLauncher.started += instance.OnRocketLauncher;
            @RocketLauncher.performed += instance.OnRocketLauncher;
            @RocketLauncher.canceled += instance.OnRocketLauncher;
            @Ultimate.started += instance.OnUltimate;
            @Ultimate.performed += instance.OnUltimate;
            @Ultimate.canceled += instance.OnUltimate;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @SwapWeapons.started -= instance.OnSwapWeapons;
            @SwapWeapons.performed -= instance.OnSwapWeapons;
            @SwapWeapons.canceled -= instance.OnSwapWeapons;
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
            @Chainsaw.started -= instance.OnChainsaw;
            @Chainsaw.performed -= instance.OnChainsaw;
            @Chainsaw.canceled -= instance.OnChainsaw;
            @Pistol.started -= instance.OnPistol;
            @Pistol.performed -= instance.OnPistol;
            @Pistol.canceled -= instance.OnPistol;
            @MachineGun.started -= instance.OnMachineGun;
            @MachineGun.performed -= instance.OnMachineGun;
            @MachineGun.canceled -= instance.OnMachineGun;
            @LightningGun.started -= instance.OnLightningGun;
            @LightningGun.performed -= instance.OnLightningGun;
            @LightningGun.canceled -= instance.OnLightningGun;
            @RailGun.started -= instance.OnRailGun;
            @RailGun.performed -= instance.OnRailGun;
            @RailGun.canceled -= instance.OnRailGun;
            @Shotgun.started -= instance.OnShotgun;
            @Shotgun.performed -= instance.OnShotgun;
            @Shotgun.canceled -= instance.OnShotgun;
            @RocketLauncher.started -= instance.OnRocketLauncher;
            @RocketLauncher.performed -= instance.OnRocketLauncher;
            @RocketLauncher.canceled -= instance.OnRocketLauncher;
            @Ultimate.started -= instance.OnUltimate;
            @Ultimate.performed -= instance.OnUltimate;
            @Ultimate.canceled -= instance.OnUltimate;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSwapWeapons(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnChainsaw(InputAction.CallbackContext context);
        void OnPistol(InputAction.CallbackContext context);
        void OnMachineGun(InputAction.CallbackContext context);
        void OnLightningGun(InputAction.CallbackContext context);
        void OnRailGun(InputAction.CallbackContext context);
        void OnShotgun(InputAction.CallbackContext context);
        void OnRocketLauncher(InputAction.CallbackContext context);
        void OnUltimate(InputAction.CallbackContext context);
    }
}
